apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: simple-http-gen
spec:
  schedule: "0 * * * *" # @hourly
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: simple-http-gen
              image: cron
              imagePullPolicy: Always
              env:
                - name: API_URL
                  valueFrom:
                    secretKeyRef:
                      key: API_URL
                      name: simple-http-secrets
                - name: API_URI
                  valueFrom:
                    secretKeyRef:
                      key: API_URI
                      name: simple-http-secrets
                - name: RAND_URL
                  valueFrom:
                    secretKeyRef:
                      key: RAND_URL
                      name: simple-http-secrets
          restartPolicy: OnFailure
