apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: simple-http-pg-stset
spec:
  serviceName: simple-http-pg-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        # persistence
        - name: postgres
          image: postgres
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: pguser
                  name: simple-http-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pgpassword
                  name: simple-http-secrets
          volumeMounts:
            - name: simple-http-pg-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: simple-http-pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
