repos:
  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # Shell
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]

  # Dockerfiles
  # - repo: https://github.com/hadolint/hadolint
  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        entry: ./tools/hadolint
        language: system
        types: [dockerfile]

  # yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml]
