# Do not deploy this again if the ingress for log_output is already deployed!

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: ping-log-shared-ingress
spec:
  rules:
    - http:
        paths:
          - path: /pingpong
            pathType: ImplementationSpecific
            backend:
              service:
                name: ping-pong-svc
                port:
                  number: 80
