# The pods seem to share this without problem...?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: simple-http-pvc-2-4
spec:
  # no pv on cloud
  # storageClassName: simple-http-pv-2-4-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
